services:
  - type: web
    name: qr-attendance-app
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "*"
      - key: CORS_ALLOW_ALL_ORIGINS
        value: "True"
    disk:
      name: attendance-media
      mountPath: /app/backend/media
      sizeGB: 1
