# Generated by Django 5.0.14 on 2026-09-06 10:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_api', '0003_event_alter_attendancesession_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('qr_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passes', to='attendance_api.event')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_passes', to='attendance_api.student')),
            ],
            options={
                'ordering': ['-id'],
                'unique_together': {('event', 'student')},
            },
        ),
    ]
