# Generated by Django 5.0.14 on 2026-09-07 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_api', '0004_eventpass'),
    ]

    operations = [
        migrations.AddField(
            model_name='smtpsetting',
            name='provider',
            field=models.CharField(default='resend', max_length=50),
        ),
        migrations.AddField(
            model_name='smtpsetting',
            name='resend_api_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='smtpsetting',
            name='from_email',
            field=models.CharField(default='onboarding@resend.dev', max_length=255),
        ),
    ]
