# Generated by Django 5.0.14 on 2026-09-07 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_api', '0005_smtpsetting_provider_smtpsetting_resend_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smtpsetting',
            name='brevo_api_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='smtpsetting',
            name='provider',
            field=models.CharField(default='brevo', max_length=50),
        ),
    ]
