# Generated by Django 5.0.14 on 2026-09-09 07:01

import attendance_api.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_api', '0006_smtpsetting_brevo_api_key_alter_smtpsetting_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smtpsetting',
            name='brevo_api_key',
            field=attendance_api.models.EncryptedCharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='smtpsetting',
            name='password',
            field=attendance_api.models.EncryptedCharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='smtpsetting',
            name='resend_api_key',
            field=attendance_api.models.EncryptedCharField(blank=True, default='', max_length=500),
        ),
    ]
